stages:
  - test # Compilation and unit tests
  - test database scripts # Testing database creation scripts
jobs:
  include:
    - stage: test
      language: java
      jdk: oraclejdk8
      sudo: false
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      before_script:
        - psql -f 'db_scripts/prepare_postgresql-core_db.sql' -U postgres
      cache:
        directories:
          - $HOME/.m2
      script: mvn clean install

    - stage: test database scripts
      language: bash
      sudo: true
      before_install:
        - .travis/bats/bats-core-installation.sh
      services:
        - docker
      script: export PATH="$PATH:.travis/bats/bats-core/bin" && bats/run_bats_test.sh

