language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  postgresql: "9.6"
services:
  - postgresql

before_script:
  - psql -f 'db_scripts/prepare_postgresql-core_db.sql' -U postgres

cache:
  directories:
    - $HOME/.m2
script: mvn clean install
