stages:
  # Compilation and unit tests
  - test
  # Testing database creation scripts
  - test database scripts
jobs:
  include:
    - stage: test
      language: java
      jdk: oraclejdk8
      sudo: false
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      before_script:
        - psql -f 'db_scripts/prepare_postgresql-core_db.sql' -U postgres
      cache:
        directories:
          - $HOME/.m2
      script: mvn clean install

    - stage: test database scripts
      language: bash
      sudo: true
      before_install:
        - .travis/bats/bats-core-installation.sh $TRAVIS_BUILD_DIR
      services:
        - docker
      script: ls -la $TRAVIS_BUILD_DIR/.travis/bats/bats-core/ && export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && which bats && bats/run_bats_test.sh

