stages:
  - test # Compilation and unit tests
  - test database scripts # Testing database creation scripts
jobs:
  include:
    - stage: test
      language: java
      jdk: oraclejdk8
      sudo: false
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      before_script:
        - psql -f 'db_scripts/prepare_postgresql-core_db.sql' -U postgres
      cache:
        directories:
          - $HOME/.m2
      script: mvn clean install

    - stage: test database scripts
      language: bash
      sudo: true
      before_install:
        - git clone https://github.com/bats-core/bats-core.git
        - git fetch --all --tags --prune
        - git checkout v1.1.0
        - bats-core/install.sh /usr/local
      services:
        - docker
      script: bats/run_bats_test.sh

